'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(), clone=v=>JSON.parse(JSON.stringify(v)), KEY='modelo-mobile-v1', CARDS=['0,1','1,1','0,N','1,N'];
const sample={version:1,title:'Loja · exemplo',entities:[{id:'cliente',name:'Cliente',x:230,y:300,attrs:[{id:'a1',name:'id_cliente',key:true},{id:'a2',name:'nome',key:false},{id:'a3',name:'email',key:false}]},{id:'pedido',name:'Pedido',x:750,y:300,attrs:[{id:'a4',name:'id_pedido',key:true},{id:'a5',name:'data',key:false},{id:'a6',name:'valor',key:false}]}],relations:[{id:'realiza',name:'realiza',from:'cliente',to:'pedido',fromCard:'0,N',toCard:'1,1',x:490,y:300}]};
let model=clone(sample),selected=null,undo=[],redo=[],view={x:0,y:0,z:1},editing=null,toastTimer;
if(window.matchMedia('(max-width:650px)').matches){model.entities[0].x=230;model.entities[0].y=210;model.entities[1].x=230;model.entities[1].y=510;model.entities[1].attrsSide='below';model.relations[0].x=230;model.relations[0].y=360;}
function validate(m){
 if(!m||m.version!==1||typeof m.title!=='string'||!m.title.trim()||m.title.length>100||!Array.isArray(m.entities)||!Array.isArray(m.relations)||m.entities.length>150||m.relations.length>300)throw Error('Este arquivo não é um modelo válido deste editor.');
 const ids=new Set(), add=id=>{if(typeof id!=='string'||!id||id.length>100||ids.has(id))throw Error('O arquivo contém identificadores inválidos.');ids.add(id);}, name=n=>{if(typeof n!=='string'||!n.trim()||n.length>60)throw Error('O arquivo contém nomes inválidos.');}, point=n=>{if(!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>100000||Math.abs(n.y)>100000)throw Error('Posição inválida no arquivo.');};
 for(const e of m.entities){add(e.id);name(e.name);point(e);if(!Array.isArray(e.attrs)||e.attrs.length>30)throw Error('Lista de atributos inválida.');for(const a of e.attrs){add(a.id);name(a.name);if(a.position!==undefined){if(!a.position||typeof a.position!=='object')throw Error('Posição de atributo inválida.');point(a.position);}if(typeof a.key!=='boolean')throw Error('Atributo inválido.');}}
 const entities=new Set(m.entities.map(e=>e.id));for(const r of m.relations){add(r.id);name(r.name);point(r);if(!entities.has(r.from)||!entities.has(r.to)||!CARDS.includes(r.fromCard)||!CARDS.includes(r.toCard))throw Error('Relacionamento inválido no arquivo.');for(const offset of [r.fromLabelOffset,r.toLabelOffset])if(offset!==undefined){if(!offset||typeof offset!=='object')throw Error('Posição de cardinalidade inválida.');point(offset);}for(const role of [r.fromRole,r.toRole])if(role!==undefined&&(typeof role!=='string'||role.length>40))throw Error('Papel inválido no relacionamento.');}
 return clone(m);
}
let storageAvailable=true;try{const saved=localStorage.getItem(KEY);if(saved)model=validate(JSON.parse(saved));}catch{storageAvailable=false;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(model));storageAvailable=true;$('saveState').textContent='Salvo neste aparelho';}catch{storageAvailable=false;$('saveState').textContent='Baixe uma cópia para salvar';}}
function checkpoint(){undo.push(clone(model));if(undo.length>60)undo.shift();redo=[];}
function mutate(fn){checkpoint();fn();persist();render();}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3600);}
function getNode(id=selected){return model.entities.find(e=>e.id===id)||model.relations.find(r=>r.id===id);}
function text(x,y,t,options=''){return `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" font-family="Arial,sans-serif" font-size="14" fill="#172b4d" ${options}>${esc(t)}</text>`;}
function attrPositions(e){return e.attrs.map((a,i)=>{const count=e.attrs.length;let ax,ay;if(count<=3){ax=e.x+(i-(count-1)/2)*130;ay=e.y+(e.attrsSide==='below'?1:-1)*(100+(count===3&&i===1?30:0));}else{const angle=(Math.PI*2*i/count)-Math.PI/2;ax=e.x+Math.cos(angle)*(150+count*4);ay=e.y+Math.sin(angle)*(110+count*4);}return {...a,x:a.position?e.x+a.position.x:ax,y:a.position?e.y+a.position.y:ay};});}
function nodeWidth(n){return Math.max(148,Math.min(520,n.name.length*8.5+38));}
function edgePoint(a,b,diamond=false){const dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return {x:a.x,y:a.y};const hx=diamond?Math.max(69,nodeWidth(a)/2):nodeWidth(a)/2,hy=diamond?43:28;const factor=diamond?1/(Math.abs(dx)/hx+Math.abs(dy)/hy):Math.min(hx/(Math.abs(dx)||.0001),hy/(Math.abs(dy)||.0001));return {x:a.x+dx*factor,y:a.y+dy*factor};}
function labelInfo(r,side){
 const e=getNode(r[side]),recursive=r.from===r.to,role=recursive?r[side+'Role']:'',caption=`${role?role+' ':''}(${r[side+'Card']})`,w=Math.max(52,caption.length*7.5+18),h=28;
 let x,y;
 if(recursive){const sign=r.x>=e.x?1:-1,bendX=e.x+sign*(nodeWidth(e)/2+38),dir=side==='from'?-1:1;x=(bendX+r.x)/2;y=(dir<0?Math.min(e.y,r.y)-90:Math.max(e.y,r.y)+90)-20;}
 else{const a=edgePoint(e,r),b=edgePoint(r,e,true),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;x=a.x+dx*.3-dy/len*24;y=a.y+dy*.3+dx/len*24;}
 const obstacles=[];for(const n of [...model.entities,...model.relations]){obstacles.push({x:n.x,y:n.y,w:nodeWidth(n)+12,h:n.attrs?70:98});if(n.attrs)for(const a of attrPositions(n))obstacles.push({x:a.x,y:a.y,w:Math.max(106,a.name.length*8+28)+12,h:56});}
 const base={x,y};for(const [dx,dy] of [[0,0],[0,-36],[0,36],[45,0],[-45,0],[0,-72],[0,72],[80,-40],[-80,40]]){const candidate={x:base.x+dx,y:base.y+dy};if(!obstacles.some(o=>Math.abs(candidate.x-o.x)<(w+o.w)/2&&Math.abs(candidate.y-o.y)<(h+o.h)/2)){x=candidate.x;y=candidate.y;break;}}
 const offset=r[side+'LabelOffset']||{x:0,y:0};return {x:x+offset.x,y:y+offset.y,w,h,caption};
}
function cardinalityMarkup(r,side,interactive){const l=labelInfo(r,side),hitW=Math.max(l.w,44/view.z),hitH=Math.max(l.h,44/view.z);return `<g ${interactive?`data-label-id="${esc(r.id)}" data-label-side="${side}" tabindex="0" role="button" aria-label="Mover cardinalidade ${esc(l.caption)} de ${esc(r.name)}, lado ${side==='from'?'A':'B'}. Arraste ou use as setas." style="cursor:move"`:''}>${interactive?`<rect x="${l.x-hitW/2}" y="${l.y-hitH/2}" width="${hitW}" height="${hitH}" fill="transparent"/>`:''}<rect x="${l.x-l.w/2}" y="${l.y-l.h/2}" width="${l.w}" height="${l.h}" rx="6" fill="white" stroke="#c5d4df"/>${text(l.x,l.y,l.caption)}</g>`;}
function diagramMarkup(selection=true){let edges='',nodes='';
 for(const r of model.relations){if(r.from===r.to){const e=model.entities.find(e=>e.id===r.from);if(!e)continue;const side=r.x>=e.x?1:-1;for(const [dir,card,role] of [[-1,r.fromCard,r.fromRole],[1,r.toCard,r.toRole]]){const ax=e.x+side*nodeWidth(e)/2,ay=e.y+dir*14,bendX=ax+side*38,loopY=dir<0?Math.min(e.y,r.y)-90:Math.max(e.y,r.y)+90;edges+=`<path d="M${ax},${ay} H${bendX} V${loopY} H${r.x} V${r.y+dir*43}" stroke="#8194a9" stroke-width="1.6" fill="none"/>`;}continue;}for(const [entityId,card] of [[r.from,r.fromCard],[r.to,r.toCard]]){const e=model.entities.find(e=>e.id===entityId);if(!e)continue;const a=edgePoint(e,r),b=edgePoint(r,e,true);edges+=`<path d="M${a.x},${a.y} L${b.x},${b.y}" stroke="#8194a9" stroke-width="1.6" fill="none"/>`;}}
 for(const e of model.entities){const attrs=attrPositions(e);for(const a of attrs){const start=edgePoint(e,a);edges+=`<path d="M${start.x},${start.y} L${a.x},${a.y}" stroke="#9babbc" stroke-width="1.3"/>`;nodes+=`<g ${selection?`data-attribute-id="${esc(a.id)}" data-owner-id="${esc(e.id)}" tabindex="0" role="button" aria-label="Mover atributo ${esc(a.name)}. Arraste ou use as setas." style="cursor:move"`:''}><ellipse cx="${a.x}" cy="${a.y}" rx="${Math.max(53,a.name.length*4+14)}" ry="22" fill="#fff" stroke="#91a5b9" stroke-width="1.3"/>${text(a.x,a.y,a.name,a.key?'text-decoration="underline" font-weight="600"':'')}</g>`;}const active=selection&&selected===e.id;nodes+=`<g data-id="${esc(e.id)}" style="cursor:move"><rect x="${e.x-nodeWidth(e)/2}" y="${e.y-28}" width="${nodeWidth(e)}" height="56" rx="3" fill="${active?'#e6f8f3':'#fff'}" stroke="${active?'#00876f':'#355675'}" stroke-width="${active?2.8:1.8}"/>${text(e.x,e.y,e.name,'font-weight="600"')}</g>`;}
 for(const r of model.relations){const active=selection&&selected===r.id,hx=Math.max(69,nodeWidth(r)/2);nodes+=`<g data-id="${esc(r.id)}" style="cursor:move"><path d="M ${r.x-hx} ${r.y} L ${r.x} ${r.y-43} L ${r.x+hx} ${r.y} L ${r.x} ${r.y+43} Z" fill="${active?'#c8f3e8':'#e9f8f3'}" stroke="#15947e" stroke-width="${active?2.8:1.8}"/>${text(r.x,r.y,r.name)}</g>`;}
 return edges+nodes+model.relations.map(r=>cardinalityMarkup(r,'from',selection)+cardinalityMarkup(r,'to',selection)).join('');
}
function render(){ $('scene').innerHTML=diagramMarkup();applyView();$('docTitle').textContent=model.title;document.title=model.title+' — Modelo Mobile';$('countLabel').textContent=`${model.entities.length} entidades · ${model.relations.length} relacionamentos`;$('empty').hidden=!!model.entities.length;const n=getNode();$('selectionBar').hidden=!n;if(n)$('selectedName').textContent=n.name;$('undoBtn').disabled=!undo.length;$('redoBtn').disabled=!redo.length;}
function applyView(){$('scene').setAttribute('transform',`translate(${view.x} ${view.y}) scale(${view.z})`);$('zoomLabel').textContent=Math.round(view.z*100)+'%';}
function bounds(){
 const pts=[];for(const e of model.entities){pts.push({x:e.x-nodeWidth(e)/2-12,y:e.y-35},{x:e.x+nodeWidth(e)/2+12,y:e.y+35});for(const a of attrPositions(e)){const rx=Math.max(53,a.name.length*4+14);pts.push({x:a.x-rx-8,y:a.y-30},{x:a.x+rx+8,y:a.y+30});}}
 for(const r of model.relations){pts.push({x:r.x-nodeWidth(r)/2-15,y:r.y-50},{x:r.x+nodeWidth(r)/2+15,y:r.y+50});if(r.from===r.to){const e=getNode(r.from),side=r.x>=e.x?1:-1,bendX=e.x+side*(nodeWidth(e)/2+38),tx=(bendX+r.x)/2,half=Math.max((r.fromRole||'').length,(r.toRole||'').length)*4+35;pts.push({x:Math.min(bendX,tx-half),y:Math.min(e.y,r.y)-120},{x:Math.max(bendX,tx+half),y:Math.max(e.y,r.y)+105});}}
 for(const r of model.relations)for(const side of ['from','to']){const l=labelInfo(r,side);pts.push({x:l.x-l.w/2-8,y:l.y-l.h/2-8},{x:l.x+l.w/2+8,y:l.y+l.h/2+8});}if(!pts.length)return {x:0,y:0,w:500,h:300};const x=Math.min(...pts.map(p=>p.x)),y=Math.min(...pts.map(p=>p.y));return {x,y,w:Math.max(...pts.map(p=>p.x))-x,h:Math.max(...pts.map(p=>p.y))-y};
}
function fit(){const b=bounds(),w=$('canvas').clientWidth,h=$('canvas').clientHeight;view.z=Math.max(.12,Math.min(1.15,(w-40)/b.w,(h-150)/b.h));view.x=(w-b.w*view.z)/2-b.x*view.z;view.y=(h-b.h*view.z)/2-b.y*view.z;applyView();}
function zoom(f,cx=$('canvas').clientWidth/2,cy=$('canvas').clientHeight/2){const z=Math.min(2.5,Math.max(.12,view.z*f));view.x=cx-(cx-view.x)*z/view.z;view.y=cy-(cy-view.y)*z/view.z;view.z=z;applyView();}
function center(){return {x:($('canvas').clientWidth/2-view.x)/view.z,y:($('canvas').clientHeight/2-view.y)/view.z};}
function entityBox(e){const points=[{x:e.x-nodeWidth(e)/2,y:e.y-28},{x:e.x+nodeWidth(e)/2,y:e.y+28}];for(const a of attrPositions(e)){const rx=Math.max(53,a.name.length*4+14);points.push({x:a.x-rx,y:a.y-22},{x:a.x+rx,y:a.y+22});}return {left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))};}
function boxVisible(b){return b.left*view.z+view.x>=20&&b.right*view.z+view.x<=$('canvas').clientWidth-20&&b.top*view.z+view.y>=100&&b.bottom*view.z+view.y<=$('canvas').clientHeight-70;}
function freeEntityPosition(name,attrs){
 const obstacles=model.entities.map(entityBox);for(const r of model.relations){obstacles.push({left:r.x-nodeWidth(r)/2,right:r.x+nodeWidth(r)/2,top:r.y-43,bottom:r.y+43});for(const side of ['from','to']){const l=labelInfo(r,side);obstacles.push({left:l.x-l.w/2,right:l.x+l.w/2,top:l.y-l.h/2,bottom:l.y+l.h/2});}}
 const origin=center();let nearest=null;
 for(let ring=0;ring<=20;ring++)for(let row=-ring;row<=ring;row++)for(let col=-ring;col<=ring;col++){if(Math.max(Math.abs(row),Math.abs(col))!==ring)continue;const point={x:origin.x+col*64,y:origin.y+row*64},b=entityBox({name,attrs,...point});if(obstacles.some(o=>b.left<o.right+36&&b.right>o.left-36&&b.top<o.bottom+36&&b.bottom>o.top-36))continue;if(boxVisible(b))return point;if(!nearest)nearest=point;}
 if(nearest)return nearest;const b=entityBox({name,attrs,x:0,y:0});return {x:Math.max(origin.x,...obstacles.map(o=>o.right))+64-b.left,y:origin.y};
}
function revealEntity(e){const b=entityBox(e);if(boxVisible(b))return;const w=$('canvas').clientWidth,h=$('canvas').clientHeight;view.z=Math.min(view.z,(w-40)/Math.max(1,b.right-b.left),Math.max(40,h-170)/Math.max(1,b.bottom-b.top));view.x=w/2-(b.left+b.right)/2*view.z;view.y=(h+30)/2-(b.top+b.bottom)/2*view.z;applyView();}
function attrRow(a={id:uid(),name:'',key:false}){return `<div class="attribute-row" data-attr-id="${esc(a.id)}"><input type="text" aria-label="Nome do atributo" placeholder="Nome do atributo" value="${esc(a.name)}" maxlength="60" required><label><input type="checkbox" ${a.key?'checked':''}>Chave</label><button type="button" data-remove-attr aria-label="Remover atributo">×</button></div>`;}
function openEntity(id,addAttribute=false){const e=model.entities.find(n=>n.id===id);editing={type:'entity',id:e?.id};$('editorKind').textContent='ENTIDADE';$('editorTitle').textContent=e?'Editar entidade':'Nova entidade';$('editorFields').innerHTML=`<label for="nodeName">Nome da entidade</label><input id="nodeName" maxlength="60" placeholder="Ex.: Cliente" required value="${esc(e?.name||'')}"><label>Atributos</label><p class="field-hint">Marque “Chave” nos atributos que identificam a entidade.</p><div id="attrs">${(e?.attrs||[]).map(attrRow).join('')}${addAttribute?attrRow():''}</div><button type="button" id="addAttr" class="add-attr">+ Adicionar atributo</button><p class="field-hint">Arraste cada atributo no diagrama para ajustar sua posição. Ao mover a entidade, os atributos acompanham.</p><label class="reset-labels"><input type="checkbox" id="resetAttributes"> Restaurar posições automáticas dos atributos</label>`;$('addAttr').onclick=()=>{if($('attrs').children.length>=30)return toast('Limite de 30 atributos por entidade.');$('attrs').insertAdjacentHTML('beforeend',attrRow());$('attrs').lastElementChild.querySelector('input').focus();};$('editor').showModal();if(addAttribute)$('attrs').lastElementChild.querySelector('input').focus();}
function openRelation(id,kind='normal'){
 const r=model.relations.find(n=>n.id===id),recursive=r?r.from===r.to:kind==='recursive';
 if(model.entities.length<(recursive?1:2))return toast(recursive?'Adicione uma entidade para criar um relacionamento recursivo.':'Adicione duas entidades para criar um relacionamento normal.');
 editing={type:'relation',id:r?.id,recursive};$('editorKind').textContent=recursive?'RELACIONAMENTO RECURSIVO':'RELACIONAMENTO NORMAL';$('editorTitle').textContent=(r?'Editar':'Novo')+' relacionamento '+(recursive?'recursivo':'normal');
 const opts=sel=>model.entities.map(e=>`<option value="${esc(e.id)}" ${e.id===sel?'selected':''}>${esc(e.name)}</option>`).join(''),cards=sel=>CARDS.map(c=>`<option ${c===sel?'selected':''}>${c}</option>`).join('');
 $('editorFields').innerHTML=`<p class="relation-summary">${recursive?'Uma entidade se relaciona com ela mesma, em dois papéis.':'Duas entidades diferentes se relacionam entre si.'}</p><label for="nodeName">Nome do relacionamento</label><input id="nodeName" maxlength="60" required placeholder="${recursive?'Ex.: supervisiona':'Ex.: realiza'}" value="${esc(r?.name||'')}">`+(recursive?
 `<label for="from">Entidade</label><select id="from">${opts(r?.from||model.entities.find(e=>e.id===selected)?.id||model.entities[0].id)}</select><div id="roles"><div class="two-col"><div><label for="fromRole">Papel A (opcional)</label><input id="fromRole" maxlength="40" placeholder="Ex.: supervisor" value="${esc(r?.fromRole||'')}"></div><div><label for="fromCard">Mín., máx.</label><select id="fromCard">${cards(r?.fromCard||'0,N')}</select></div></div><div class="two-col"><div><label for="toRole">Papel B (opcional)</label><input id="toRole" maxlength="40" placeholder="Ex.: subordinado" value="${esc(r?.toRole||'')}"></div><div><label for="toCard">Mín., máx.</label><select id="toCard">${cards(r?.toCard||'0,1')}</select></div></div></div><p class="field-hint">Ex.: um funcionário no papel de supervisor (0,N) pode supervisionar vários funcionários. No papel de subordinado (0,1), pode ter até um supervisor.</p>`:
 `<div class="two-col"><div><label for="from">Entidade A</label><select id="from">${opts(r?.from||model.entities[0].id)}</select></div><div><label for="fromCard">Mín., máx.</label><select id="fromCard">${cards(r?.fromCard||'0,N')}</select></div></div><div class="two-col"><div><label for="to">Entidade B</label><select id="to">${opts(r?.to||model.entities[1].id)}</select></div><div><label for="toCard">Mín., máx.</label><select id="toCard">${cards(r?.toCard||'1,1')}</select></div></div><p class="field-hint">Ex.: Cliente (0,N) pode realizar vários pedidos. Pedido (1,1) pertence a um cliente.</p>`);
 if(!recursive){const updateOptions=()=>{const to=$('to');for(const option of to.options)option.disabled=option.value===$('from').value;if(to.value===$('from').value)to.value=[...to.options].find(o=>!o.disabled).value;};$('from').onchange=updateOptions;updateOptions();}
 $('editorFields').insertAdjacentHTML('beforeend','<p class="field-hint">Arraste as cardinalidades no diagrama para ajustar a posição.</p><label class="reset-labels"><input type="checkbox" id="resetLabels"> Restaurar posições automáticas</label>');$('editor').showModal();
}
function editSelected(){const e=getNode();if(e)(e.attrs?openEntity:openRelation)(e.id);}
document.addEventListener('click',ev=>{const close=ev.target.closest('[data-close]');if(close)$(close.dataset.close).close();const remove=ev.target.closest('[data-remove-attr]');if(remove)remove.parentElement.remove();});
$('editForm').onsubmit=ev=>{
 ev.preventDefault();const name=$('nodeName').value.trim();if(!name)return toast('Digite um nome.');
 if(editing.type==='title'){mutate(()=>model.title=name);$('editor').close();return;}
 if(editing.type==='entity'){
 const attrs=[...$('attrs').children].map(row=>({...getNode(editing.id)?.attrs?.find(a=>a.id===row.dataset.attrId),id:row.dataset.attrId,name:row.querySelector('input[type=text]').value.trim(),key:row.querySelector('input[type=checkbox]').checked}));if($('resetAttributes').checked)for(const a of attrs)delete a.position;if(attrs.some(a=>!a.name))return toast('Preencha o nome de todos os atributos.');if(!editing.id&&model.entities.length>=150)return toast('Limite de 150 entidades por modelo.');
 mutate(()=>{if(editing.id)Object.assign(getNode(editing.id),{name,attrs});else{const e={id:uid(),name,attrs,...freeEntityPosition(name,attrs)};model.entities.push(e);selected=e.id;}});if(!editing.id)revealEntity(getNode());
 }else{
 if(!editing.id&&model.relations.length>=300)return toast('Limite de 300 relacionamentos por modelo.');
 const from=$('from').value,to=editing.recursive?from:$('to').value;
 if(!editing.recursive&&from===to)return toast('O relacionamento normal precisa de duas entidades diferentes.');
 const data={name,from,to,fromCard:$('fromCard').value,toCard:$('toCard').value,fromRole:editing.recursive?$('fromRole').value.trim():'',toRole:editing.recursive?$('toRole').value.trim():''};
 mutate(()=>{if(editing.id){const r=getNode(editing.id),wasRecursive=r.from===r.to;Object.assign(r,data);if($('resetLabels').checked){delete r.fromLabelOffset;delete r.toLabelOffset;}if(!wasRecursive&&r.from===r.to){const e=getNode(r.from);r.x=e.x+nodeWidth(e)/2+180;r.y=e.y;}}else{const a=getNode(data.from),b=getNode(data.to),recursive=data.from===data.to,r={...data,id:uid(),x:recursive?a.x+nodeWidth(a)/2+180:(a.x+b.x)/2,y:(a.y+b.y)/2};model.relations.push(r);selected=r.id;}});
 }$('editor').close();if(editing.type==='relation'&&getNode()?.from===getNode()?.to)fit();
};
function confirmAction(title,message,fn){$('confirmTitle').textContent=title;$('confirmText').textContent=message;$('confirmDialog').returnValue='cancel';$('confirmDialog').onclose=()=>{if($('confirmDialog').returnValue==='yes')fn();};$('confirmDialog').showModal();}
function deleteSelected(){const n=getNode();if(!n)return;confirmAction('Excluir '+n.name+'?',n.attrs?'Os atributos e relacionamentos ligados a esta entidade também serão excluídos. Você pode desfazer.':'Você pode desfazer esta exclusão.',()=>mutate(()=>{model.entities=model.entities.filter(e=>e.id!==n.id);model.relations=model.relations.filter(r=>r.id!==n.id&&r.from!==n.id&&r.to!==n.id);selected=null;}));}
function doUndo(){if(!undo.length)return;redo.push(clone(model));model=undo.pop();selected=null;persist();render();}function doRedo(){if(!redo.length)return;undo.push(clone(model));model=redo.pop();selected=null;persist();render();}
function download(content,type,ext){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=(model.title.replace(/[^\p{L}\p{N}_-]+/gu,'-')||'modelo')+'.'+ext;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('entityBtn').onclick=()=>openEntity();$('emptyAdd').onclick=()=>openEntity();$('relationBtn').onclick=()=>openRelation(undefined,'normal');$('recursiveBtn').onclick=()=>openRelation(undefined,'recursive');$('attributeBtn').onclick=()=>{const e=getNode();if(e?.attrs)openEntity(e.id,true);else if(model.entities.length===1)openEntity(model.entities[0].id,true);else toast('Selecione uma entidade no diagrama para adicionar atributos.');};$('editBtn').onclick=editSelected;$('deleteBtn').onclick=deleteSelected;$('undoBtn').onclick=doUndo;$('redoBtn').onclick=doRedo;$('zoomIn').onclick=()=>zoom(1.2);$('zoomOut').onclick=()=>zoom(1/1.2);$('fitBtn').onclick=fit;$('menuBtn').onclick=()=>$('menu').showModal();
$('titleBtn').onclick=()=>{editing={type:'title'};$('editorKind').textContent='MODELO';$('editorTitle').textContent='Renomear modelo';$('editorFields').innerHTML=`<label for="nodeName">Nome do modelo</label><input id="nodeName" required maxlength="100" value="${esc(model.title)}">`;$('editor').showModal();};
$('exportJson').onclick=()=>{download(JSON.stringify(model,null,2),'application/json','json');$('menu').close();toast('Cópia editável preparada para download.');};
$('exportSvg').onclick=()=>{const b=bounds();download(`<svg xmlns="http://www.w3.org/2000/svg" width="${Math.ceil(b.w+80)}" height="${Math.ceil(b.h+100)}" viewBox="${b.x-40} ${b.y-60} ${b.w+80} ${b.h+100}"><title>${esc(model.title)}</title><rect x="${b.x-40}" y="${b.y-60}" width="${b.w+80}" height="${b.h+100}" fill="white"/>${text(b.x+b.w/2,b.y-32,model.title,'font-weight="600"')}${diagramMarkup(false)}</svg>`,'image/svg+xml','svg');$('menu').close();toast('Imagem SVG preparada para download.');};
$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file)return;if(file.size>2000000)return toast('O arquivo deve ter até 2 MB.');try{const incoming=validate(JSON.parse(await file.text()));$('menu').close();confirmAction('Abrir outro modelo?','O modelo atual será substituído. Baixe uma cópia antes, se necessário. Você também pode desfazer.',()=>{mutate(()=>{model=incoming;selected=null;});fit();toast('Modelo aberto.');});}catch(e){toast(e instanceof SyntaxError?'Não foi possível ler este JSON.':e.message);}};
$('newBtn').onclick=()=>{$('menu').close();confirmAction('Criar um novo modelo?','O modelo atual será substituído. Baixe uma cópia antes, se necessário. Você também pode desfazer.',()=>{mutate(()=>{model={version:1,title:'Modelo sem título',entities:[],relations:[]};selected=null;});fit();});};
$('listBtn').onclick=()=>{$('menu').close();$('elementList').innerHTML=[...model.entities,...model.relations].map(n=>`<button data-edit-id="${esc(n.id)}">${n.attrs?'□':'◇'} ${esc(n.name)}</button>`).join('')||'<p>Nenhum elemento ainda. Adicione uma entidade.</p>';$('listDialog').showModal();};$('elementList').onclick=ev=>{const el=ev.target.closest('[data-edit-id]');if(el){selected=el.dataset.editId;render();$('listDialog').close();editSelected();}};
const pointers=new Map();let gesture=null;
function localPoint(ev){const r=$('canvas').getBoundingClientRect();return {x:ev.clientX-r.left,y:ev.clientY-r.top};}
function pinchState(){const [a,b]=[...pointers.values()];return {x:(a.x+b.x)/2,y:(a.y+b.y)/2,d:Math.hypot(a.x-b.x,a.y-b.y)};}
$('canvas').onpointerdown=ev=>{if(ev.button!==0&&ev.pointerType==='mouse')return;const p=localPoint(ev);pointers.set(ev.pointerId,p);$('canvas').setPointerCapture(ev.pointerId);if(pointers.size===2){if(gesture?.changed){persist();render();}gesture={type:'pinch',...pinchState(),view:{...view}};return;}if(pointers.size>2)return;const label=ev.target.closest('[data-label-id]'),attribute=ev.target.closest('[data-attribute-id]'),id=label?.dataset.labelId||attribute?.dataset.ownerId||ev.target.closest('[data-id]')?.dataset.id;selected=id||null;const n=getNode(),side=label?.dataset.labelSide,attrId=attribute?.dataset.attributeId,attr=attribute?attrPositions(n).find(a=>a.id===attrId):null;gesture={type:label?'label':attribute?'attribute':n?'node':'pan',id,side,attrId,start:p,view:{...view},node:label?{...(n[side+'LabelOffset']||{x:0,y:0})}:attr?{x:attr.x-n.x,y:attr.y-n.y}:n?{x:n.x,y:n.y}:null,changed:false};render();};
$('canvas').onpointermove=ev=>{if(!pointers.has(ev.pointerId)||!gesture)return;const p=localPoint(ev);pointers.set(ev.pointerId,p);if(gesture.type==='pinch'&&pointers.size>=2){const s=pinchState(),old=gesture.view,z=Math.min(2.5,Math.max(.12,old.z*s.d/Math.max(gesture.d,1)));view={z,x:s.x-(gesture.x-old.x)*z/old.z,y:s.y-(gesture.y-old.y)*z/old.z};applyView();return;}if(pointers.size!==1||gesture.type==='pinch')return;const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(!gesture.changed&&Math.hypot(dx,dy)<4)return;if(gesture.type==='label'){if(!gesture.changed)checkpoint();const r=getNode(gesture.id);if(r)r[gesture.side+'LabelOffset']={x:gesture.node.x+dx/view.z,y:gesture.node.y+dy/view.z};}else if(gesture.type==='attribute'){if(!gesture.changed)checkpoint();const a=getNode(gesture.id)?.attrs.find(a=>a.id===gesture.attrId);if(a)a.position={x:gesture.node.x+dx/view.z,y:gesture.node.y+dy/view.z};}else if(gesture.type==='node'){if(!gesture.changed)checkpoint();const n=getNode(gesture.id);if(n){n.x=gesture.node.x+dx/view.z;n.y=gesture.node.y+dy/view.z;}}else{view.x=gesture.view.x+dx;view.y=gesture.view.y+dy;}gesture.changed=true;render();};
function pointerEnd(ev){pointers.delete(ev.pointerId);if(gesture?.changed&&['node','label','attribute'].includes(gesture.type))persist();if(pointers.size===1){const p=[...pointers.values()][0];gesture={type:'pan',start:p,view:{...view},changed:false};}else if(!pointers.size)gesture=null;}
$('canvas').onpointerup=pointerEnd;$('canvas').onpointercancel=pointerEnd;$('canvas').ondblclick=ev=>{const id=ev.target.closest('[data-attribute-id]')?.dataset.ownerId||ev.target.closest('[data-id]')?.dataset.id;if(id){selected=id;editSelected();}};$('canvas').addEventListener('wheel',ev=>{ev.preventDefault();const p=localPoint(ev);zoom(Math.exp(-ev.deltaY*.001),p.x,p.y);},{passive:false});
document.addEventListener('keydown',ev=>{const attribute=ev.target.closest?.('[data-attribute-id]');if(attribute&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const id=attribute.dataset.ownerId,attrId=attribute.dataset.attributeId,step=ev.shiftKey?1:10;mutate(()=>{const e=getNode(id),a=e.attrs.find(a=>a.id===attrId),pos=attrPositions(e).find(a=>a.id===attrId);a.position={x:pos.x-e.x+(ev.key==='ArrowRight'?step:ev.key==='ArrowLeft'?-step:0),y:pos.y-e.y+(ev.key==='ArrowDown'?step:ev.key==='ArrowUp'?-step:0)};});[...document.querySelectorAll('[data-attribute-id]')].find(el=>el.dataset.attributeId===attrId)?.focus();return;}const label=ev.target.closest?.('[data-label-id]');if(label&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const id=label.dataset.labelId,side=label.dataset.labelSide,step=ev.shiftKey?1:10;mutate(()=>{const r=getNode(id),offset=r[side+'LabelOffset']||{x:0,y:0};r[side+'LabelOffset']={x:offset.x+(ev.key==='ArrowRight'?step:ev.key==='ArrowLeft'?-step:0),y:offset.y+(ev.key==='ArrowDown'?step:ev.key==='ArrowUp'?-step:0)};});[...document.querySelectorAll('[data-label-id]')].find(el=>el.dataset.labelId===id&&el.dataset.labelSide===side)?.focus();return;}if(document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(ev.target.tagName))return;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?doRedo():doUndo();}if(ev.key==='Delete')deleteSelected();if(ev.key==='Escape'){selected=null;render();}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(fit,100);});render();requestAnimationFrame(fit);if(!storageAvailable){$('saveState').textContent='Baixe uma cópia para salvar';toast('O salvamento anterior não pôde ser lido. Use Baixar modelo para guardar uma cópia.');}else persist();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_diagram',title:'Ler modelo conceitual',description:'Retorna o diagrama aberto no editor, com entidades, atributos, relacionamentos e cardinalidades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Use um objeto vazio.');return clone(model);}})).catch(()=>{});}catch{}}

